### ISSUE TITLE
Add support for `:import`/`:export` rules - vscode-css-modules

### ISSUE THREAD

**Issue by sixclones** [AndrewLeedham/vscode-extensions#109]
Hi,

I found that you can [import](https://github.com/css-modules/icss#import)/[export](https://github.com/css-modules/icss#export) classes with ICSS (a subset of CSS Modules).<br />
It would be nice to add support for those two keywords.

Thanks

**Comment by AndrewLeedham** [comment]
Hi @sixclones happy for you fork and release and icss version. But that is not something I am looking to maintain here.
